// generated by "sampctl package init"
#include <a_samp>
#include <rndwstLoadingBar>
main() 
{
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
}

YCMD:test(playerid, params[], help) 
{
    ShowPlayerLoadingBar(playerid, "Test", "Ini Info", 5000);
    return 1;
}

LoadingBar:Test(playerid) 
{
    SendClientMessage(playerid, -1, "Kuntul");
    return 1;
}
